version: "3.7"
services:
  client:
    container_name: client
    build: "./client/"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/client"
#      - "./client/node_modules:/client/node_modules"
      - "node_modules:/client/node_modules"
    networks: ["lottery"]

volumes:
  node_modules:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./client/node_modules
networks:
  lottery:
    name: lottery
