version: "3.8"
services:
  client:
    container_name: client
    build: "./client/"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/client"
    networks: ["lottery"]

  smart-contracts:
    container_name: smart-contracts
    build: "smart-contracts/"
    ports:
      - "8545:8545"
    volumes:
      - "./smart-contracts:/smart-contracts"
    networks: ["lottery"]

networks:
  lottery:
    name: lottery
